INSERT INTO Categories (CategoryID, CategoryName) VALUES (1, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (2, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (3, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (4, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (5, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (6, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (7, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (8, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (9, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (10, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (11, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (12, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (13, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (14, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (15, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (16, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (17, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (18, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (19, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (20, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (21, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (22, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (23, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (24, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (25, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (26, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (27, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (28, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (29, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (30, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (31, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (32, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (33, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (34, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (35, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (36, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (37, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (38, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (39, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (40, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (41, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (42, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (43, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (44, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (45, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (46, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (47, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (48, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (49, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (50, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (51, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (52, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (53, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (54, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (55, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (56, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (57, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (58, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (59, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (60, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (61, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (62, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (63, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (64, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (65, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (66, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (67, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (68, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (69, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (70, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (71, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (72, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (73, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (74, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (75, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (76, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (77, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (78, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (79, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (80, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (81, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (82, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (83, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (84, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (85, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (86, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (87, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (88, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (89, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (90, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (91, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (92, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (93, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (94, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (95, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (96, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (97, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (98, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (99, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (100, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (101, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (102, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (103, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (104, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (105, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (106, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (107, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (108, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (109, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (110, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (111, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (112, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (113, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (114, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (115, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (116, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (117, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (118, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (119, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (120, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (121, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (122, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (123, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (124, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (125, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (126, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (127, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (128, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (129, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (130, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (131, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (132, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (133, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (134, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (135, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (136, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (137, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (138, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (139, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (140, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (141, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (142, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (143, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (144, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (145, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (146, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (147, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (148, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (149, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (150, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (151, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (152, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (153, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (154, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (155, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (156, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (157, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (158, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (159, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (160, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (161, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (162, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (163, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (164, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (165, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (166, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (167, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (168, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (169, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (170, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (171, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (172, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (173, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (174, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (175, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (176, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (177, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (178, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (179, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (180, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (181, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (182, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (183, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (184, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (185, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (186, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (187, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (188, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (189, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (190, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (191, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (192, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (193, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (194, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (195, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (196, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (197, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (198, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (199, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (200, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (201, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (202, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (203, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (204, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (205, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (206, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (207, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (208, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (209, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (210, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (211, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (212, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (213, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (214, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (215, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (216, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (217, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (218, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (219, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (220, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (221, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (222, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (223, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (224, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (225, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (226, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (227, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (228, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (229, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (230, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (231, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (232, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (233, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (234, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (235, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (236, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (237, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (238, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (239, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (240, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (241, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (242, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (243, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (244, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (245, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (246, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (247, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (248, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (249, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (250, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (251, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (252, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (253, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (254, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (255, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (256, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (257, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (258, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (259, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (260, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (261, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (262, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (263, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (264, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (265, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (266, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (267, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (268, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (269, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (270, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (271, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (272, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (273, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (274, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (275, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (276, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (277, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (278, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (279, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (280, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (281, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (282, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (283, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (284, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (285, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (286, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (287, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (288, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (289, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (290, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (291, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (292, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (293, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (294, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (295, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (296, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (297, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (298, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (299, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (300, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (301, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (302, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (303, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (304, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (305, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (306, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (307, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (308, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (309, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (310, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (311, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (312, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (313, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (314, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (315, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (316, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (317, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (318, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (319, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (320, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (321, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (322, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (323, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (324, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (325, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (326, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (327, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (328, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (329, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (330, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (331, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (332, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (333, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (334, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (335, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (336, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (337, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (338, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (339, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (340, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (341, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (342, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (343, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (344, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (345, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (346, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (347, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (348, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (349, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (350, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (351, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (352, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (353, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (354, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (355, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (356, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (357, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (358, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (359, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (360, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (361, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (362, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (363, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (364, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (365, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (366, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (367, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (368, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (369, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (370, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (371, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (372, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (373, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (374, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (375, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (376, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (377, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (378, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (379, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (380, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (381, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (382, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (383, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (384, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (385, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (386, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (387, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (388, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (389, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (390, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (391, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (392, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (393, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (394, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (395, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (396, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (397, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (398, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (399, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (400, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (401, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (402, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (403, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (404, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (405, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (406, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (407, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (408, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (409, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (410, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (411, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (412, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (413, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (414, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (415, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (416, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (417, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (418, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (419, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (420, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (421, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (422, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (423, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (424, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (425, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (426, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (427, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (428, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (429, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (430, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (431, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (432, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (433, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (434, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (435, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (436, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (437, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (438, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (439, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (440, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (441, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (442, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (443, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (444, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (445, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (446, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (447, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (448, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (449, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (450, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (451, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (452, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (453, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (454, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (455, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (456, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (457, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (458, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (459, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (460, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (461, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (462, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (463, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (464, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (465, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (466, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (467, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (468, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (469, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (470, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (471, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (472, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (473, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (474, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (475, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (476, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (477, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (478, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (479, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (480, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (481, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (482, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (483, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (484, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (485, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (486, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (487, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (488, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (489, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (490, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (491, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (492, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (493, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (494, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (495, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (496, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (497, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (498, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (499, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (500, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (501, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (502, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (503, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (504, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (505, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (506, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (507, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (508, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (509, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (510, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (511, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (512, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (513, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (514, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (515, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (516, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (517, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (518, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (519, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (520, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (521, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (522, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (523, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (524, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (525, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (526, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (527, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (528, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (529, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (530, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (531, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (532, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (533, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (534, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (535, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (536, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (537, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (538, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (539, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (540, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (541, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (542, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (543, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (544, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (545, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (546, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (547, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (548, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (549, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (550, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (551, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (552, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (553, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (554, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (555, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (556, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (557, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (558, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (559, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (560, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (561, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (562, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (563, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (564, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (565, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (566, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (567, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (568, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (569, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (570, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (571, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (572, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (573, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (574, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (575, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (576, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (577, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (578, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (579, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (580, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (581, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (582, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (583, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (584, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (585, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (586, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (587, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (588, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (589, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (590, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (591, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (592, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (593, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (594, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (595, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (596, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (597, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (598, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (599, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (600, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (601, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (602, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (603, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (604, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (605, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (606, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (607, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (608, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (609, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (610, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (611, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (612, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (613, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (614, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (615, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (616, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (617, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (618, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (619, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (620, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (621, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (622, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (623, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (624, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (625, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (626, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (627, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (628, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (629, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (630, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (631, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (632, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (633, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (634, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (635, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (636, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (637, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (638, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (639, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (640, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (641, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (642, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (643, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (644, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (645, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (646, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (647, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (648, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (649, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (650, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (651, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (652, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (653, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (654, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (655, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (656, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (657, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (658, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (659, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (660, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (661, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (662, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (663, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (664, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (665, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (666, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (667, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (668, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (669, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (670, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (671, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (672, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (673, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (674, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (675, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (676, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (677, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (678, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (679, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (680, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (681, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (682, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (683, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (684, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (685, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (686, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (687, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (688, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (689, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (690, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (691, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (692, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (693, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (694, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (695, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (696, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (697, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (698, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (699, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (700, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (701, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (702, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (703, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (704, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (705, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (706, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (707, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (708, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (709, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (710, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (711, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (712, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (713, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (714, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (715, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (716, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (717, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (718, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (719, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (720, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (721, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (722, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (723, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (724, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (725, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (726, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (727, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (728, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (729, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (730, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (731, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (732, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (733, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (734, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (735, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (736, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (737, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (738, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (739, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (740, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (741, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (742, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (743, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (744, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (745, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (746, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (747, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (748, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (749, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (750, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (751, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (752, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (753, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (754, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (755, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (756, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (757, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (758, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (759, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (760, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (761, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (762, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (763, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (764, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (765, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (766, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (767, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (768, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (769, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (770, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (771, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (772, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (773, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (774, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (775, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (776, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (777, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (778, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (779, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (780, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (781, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (782, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (783, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (784, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (785, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (786, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (787, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (788, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (789, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (790, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (791, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (792, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (793, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (794, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (795, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (796, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (797, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (798, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (799, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (800, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (801, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (802, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (803, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (804, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (805, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (806, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (807, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (808, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (809, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (810, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (811, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (812, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (813, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (814, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (815, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (816, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (817, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (818, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (819, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (820, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (821, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (822, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (823, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (824, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (825, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (826, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (827, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (828, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (829, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (830, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (831, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (832, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (833, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (834, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (835, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (836, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (837, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (838, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (839, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (840, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (841, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (842, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (843, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (844, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (845, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (846, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (847, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (848, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (849, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (850, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (851, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (852, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (853, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (854, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (855, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (856, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (857, 'Gaming');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (858, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (859, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (860, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (861, 'Sports Equipment');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (862, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (863, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (864, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (865, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (866, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (867, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (868, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (869, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (870, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (871, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (872, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (873, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (874, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (875, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (876, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (877, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (878, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (879, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (880, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (881, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (882, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (883, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (884, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (885, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (886, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (887, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (888, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (889, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (890, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (891, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (892, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (893, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (894, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (895, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (896, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (897, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (898, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (899, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (900, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (901, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (902, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (903, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (904, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (905, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (906, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (907, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (908, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (909, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (910, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (911, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (912, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (913, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (914, 'Motorcycle Parts');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (915, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (916, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (917, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (918, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (919, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (920, 'Watches');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (921, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (922, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (923, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (924, 'Appliances');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (925, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (926, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (927, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (928, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (929, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (930, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (931, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (932, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (933, 'Smart Home Devices');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (934, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (935, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (936, 'Educational Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (937, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (938, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (939, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (940, 'Jewelry');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (941, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (942, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (943, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (944, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (945, 'Clothing - Men');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (946, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (947, 'Art Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (948, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (949, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (950, 'Beauty & Cosmetics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (951, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (952, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (953, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (954, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (955, 'Home & Kitchen');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (956, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (957, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (958, 'Clothing - Women');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (959, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (960, 'Books');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (961, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (962, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (963, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (964, 'Electronics');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (965, 'Furniture');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (966, 'Groceries');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (967, 'Laptops');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (968, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (969, 'Baby Products');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (970, 'Health & Wellness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (971, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (972, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (973, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (974, 'Toys');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (975, 'Luggage');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (976, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (977, 'Travel Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (978, 'Craft Materials');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (979, 'Cameras');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (980, 'Mobile Phones');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (981, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (982, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (983, 'Snacks');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (984, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (985, 'Fitness');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (986, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (987, 'Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (988, 'Computer Accessories');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (989, 'Shoes');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (990, 'Garden Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (991, 'Office Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (992, 'Music Instruments');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (993, 'Outdoor Gear');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (994, 'Beverages');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (995, 'Tablets');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (996, 'Hardware Tools');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (997, 'Automotive');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (998, 'Pet Supplies');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (999, 'Clothing - Kids');
INSERT INTO Categories (CategoryID, CategoryName) VALUES (1000, 'Smart Home Devices');
